name = "Calendars"
uuid = "2e69b1bb-2c9c-41e6-ab4b-04f4c0f206b8"
authors = ["PeterLuschny"]
version = "0.6.4"

# In fact "Calendars" is independent of "Dates".
# It only uses the line "using Dates: yearmonthday, now"
# in runtests.jl and InteractiveCalendar.jl in
# examples which can easily be omitted.
[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "1.6"
